// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/mobile.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_MobileAgentChannelPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileAgentChannel;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_MobilePortForwardPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobilePortForward;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_MobileSshSessionPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileSshSession;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_MobileTerminalPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileTerminal;

  @protected
  MobileAgentChannel
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileAgentChannel(
    dynamic raw,
  );

  @protected
  MobilePortForward
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobilePortForward(
    dynamic raw,
  );

  @protected
  MobileSshSession
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileSshSession(
    dynamic raw,
  );

  @protected
  MobileTerminal
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileTerminal(
    dynamic raw,
  );

  @protected
  MobileAgentChannel
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileAgentChannel(
    dynamic raw,
  );

  @protected
  MobilePortForward
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobilePortForward(
    dynamic raw,
  );

  @protected
  MobileSshSession
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileSshSession(
    dynamic raw,
  );

  @protected
  MobileTerminal
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileTerminal(
    dynamic raw,
  );

  @protected
  MobileAgentChannel
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileAgentChannel(
    dynamic raw,
  );

  @protected
  MobilePortForward
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobilePortForward(
    dynamic raw,
  );

  @protected
  MobileSshSession
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileSshSession(
    dynamic raw,
  );

  @protected
  MobileTerminal
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileTerminal(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  BridgeAuthentication dco_decode_box_autoadd_bridge_authentication(
    dynamic raw,
  );

  @protected
  BridgeConnectionConfig dco_decode_box_autoadd_bridge_connection_config(
    dynamic raw,
  );

  @protected
  BridgeDeviceApprovalRequestKey
  dco_decode_box_autoadd_bridge_device_approval_request_key(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BridgeAgentInstallResult dco_decode_bridge_agent_install_result(dynamic raw);

  @protected
  BridgeAuthentication dco_decode_bridge_authentication(dynamic raw);

  @protected
  BridgeCommandOutput dco_decode_bridge_command_output(dynamic raw);

  @protected
  BridgeConnectionConfig dco_decode_bridge_connection_config(dynamic raw);

  @protected
  BridgeContentKeyInitialization dco_decode_bridge_content_key_initialization(
    dynamic raw,
  );

  @protected
  BridgeContentKeyStatus dco_decode_bridge_content_key_status(dynamic raw);

  @protected
  BridgeDeviceApprovalPackage dco_decode_bridge_device_approval_package(
    dynamic raw,
  );

  @protected
  BridgeDeviceApprovalRequestKey dco_decode_bridge_device_approval_request_key(
    dynamic raw,
  );

  @protected
  BridgeHostKey dco_decode_bridge_host_key(dynamic raw);

  @protected
  BridgeRecoveryKeyRotation dco_decode_bridge_recovery_key_rotation(
    dynamic raw,
  );

  @protected
  BridgeTerminalEvent dco_decode_bridge_terminal_event(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  BridgeDeviceApprovalRequestKey?
  dco_decode_opt_box_autoadd_bridge_device_approval_request_key(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  MobileAgentChannel
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileAgentChannel(
    SseDeserializer deserializer,
  );

  @protected
  MobilePortForward
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobilePortForward(
    SseDeserializer deserializer,
  );

  @protected
  MobileSshSession
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileSshSession(
    SseDeserializer deserializer,
  );

  @protected
  MobileTerminal
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileTerminal(
    SseDeserializer deserializer,
  );

  @protected
  MobileAgentChannel
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileAgentChannel(
    SseDeserializer deserializer,
  );

  @protected
  MobilePortForward
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobilePortForward(
    SseDeserializer deserializer,
  );

  @protected
  MobileSshSession
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileSshSession(
    SseDeserializer deserializer,
  );

  @protected
  MobileTerminal
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileTerminal(
    SseDeserializer deserializer,
  );

  @protected
  MobileAgentChannel
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileAgentChannel(
    SseDeserializer deserializer,
  );

  @protected
  MobilePortForward
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobilePortForward(
    SseDeserializer deserializer,
  );

  @protected
  MobileSshSession
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileSshSession(
    SseDeserializer deserializer,
  );

  @protected
  MobileTerminal
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileTerminal(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  BridgeAuthentication sse_decode_box_autoadd_bridge_authentication(
    SseDeserializer deserializer,
  );

  @protected
  BridgeConnectionConfig sse_decode_box_autoadd_bridge_connection_config(
    SseDeserializer deserializer,
  );

  @protected
  BridgeDeviceApprovalRequestKey
  sse_decode_box_autoadd_bridge_device_approval_request_key(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BridgeAgentInstallResult sse_decode_bridge_agent_install_result(
    SseDeserializer deserializer,
  );

  @protected
  BridgeAuthentication sse_decode_bridge_authentication(
    SseDeserializer deserializer,
  );

  @protected
  BridgeCommandOutput sse_decode_bridge_command_output(
    SseDeserializer deserializer,
  );

  @protected
  BridgeConnectionConfig sse_decode_bridge_connection_config(
    SseDeserializer deserializer,
  );

  @protected
  BridgeContentKeyInitialization sse_decode_bridge_content_key_initialization(
    SseDeserializer deserializer,
  );

  @protected
  BridgeContentKeyStatus sse_decode_bridge_content_key_status(
    SseDeserializer deserializer,
  );

  @protected
  BridgeDeviceApprovalPackage sse_decode_bridge_device_approval_package(
    SseDeserializer deserializer,
  );

  @protected
  BridgeDeviceApprovalRequestKey sse_decode_bridge_device_approval_request_key(
    SseDeserializer deserializer,
  );

  @protected
  BridgeHostKey sse_decode_bridge_host_key(SseDeserializer deserializer);

  @protected
  BridgeRecoveryKeyRotation sse_decode_bridge_recovery_key_rotation(
    SseDeserializer deserializer,
  );

  @protected
  BridgeTerminalEvent sse_decode_bridge_terminal_event(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  BridgeDeviceApprovalRequestKey?
  sse_decode_opt_box_autoadd_bridge_device_approval_request_key(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileAgentChannel(
    MobileAgentChannel self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobilePortForward(
    MobilePortForward self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileSshSession(
    MobileSshSession self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileTerminal(
    MobileTerminal self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileAgentChannel(
    MobileAgentChannel self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobilePortForward(
    MobilePortForward self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileSshSession(
    MobileSshSession self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileTerminal(
    MobileTerminal self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileAgentChannel(
    MobileAgentChannel self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobilePortForward(
    MobilePortForward self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileSshSession(
    MobileSshSession self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileTerminal(
    MobileTerminal self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bridge_authentication(
    BridgeAuthentication self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bridge_connection_config(
    BridgeConnectionConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bridge_device_approval_request_key(
    BridgeDeviceApprovalRequestKey self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_agent_install_result(
    BridgeAgentInstallResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_authentication(
    BridgeAuthentication self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_command_output(
    BridgeCommandOutput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_connection_config(
    BridgeConnectionConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_content_key_initialization(
    BridgeContentKeyInitialization self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_content_key_status(
    BridgeContentKeyStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_device_approval_package(
    BridgeDeviceApprovalPackage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_device_approval_request_key(
    BridgeDeviceApprovalRequestKey self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_host_key(BridgeHostKey self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_recovery_key_rotation(
    BridgeRecoveryKeyRotation self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_terminal_event(
    BridgeTerminalEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bridge_device_approval_request_key(
    BridgeDeviceApprovalRequestKey? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileAgentChannel(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileAgentChannel(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileAgentChannel(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileAgentChannel(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobilePortForward(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobilePortForward(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobilePortForward(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobilePortForward(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileSshSession(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileSshSession(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileSshSession(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileSshSession(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileTerminal(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileTerminal(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileTerminal(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileTerminal(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileAgentChannel(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileAgentChannel(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobilePortForward(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobilePortForward(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileSshSession(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileSshSession(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileTerminal(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileTerminal(
    int ptr,
  );
}
