// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'mobile.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `bounded_timeout`, `validate_host_and_port`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`

Future<String> coreApiVersion() =>
    RustLib.instance.api.crateApiMobileCoreApiVersion();

Future<Uint8List> generateDeviceVaultKey() =>
    RustLib.instance.api.crateApiMobileGenerateDeviceVaultKey();

Future<BridgeContentKeyStatus> contentKeyStatus({
  required String vaultPath,
  required String accountId,
  required List<int> deviceVaultKey,
}) => RustLib.instance.api.crateApiMobileContentKeyStatus(
  vaultPath: vaultPath,
  accountId: accountId,
  deviceVaultKey: deviceVaultKey,
);

Future<BridgeContentKeyInitialization> initializeContentKey({
  required String vaultPath,
  required String accountId,
  required List<int> deviceVaultKey,
}) => RustLib.instance.api.crateApiMobileInitializeContentKey(
  vaultPath: vaultPath,
  accountId: accountId,
  deviceVaultKey: deviceVaultKey,
);

Future<void> acknowledgeRecoveryKeySaved({
  required String vaultPath,
  required String accountId,
  required List<int> deviceVaultKey,
}) => RustLib.instance.api.crateApiMobileAcknowledgeRecoveryKeySaved(
  vaultPath: vaultPath,
  accountId: accountId,
  deviceVaultKey: deviceVaultKey,
);

Future<void> discardPendingContentKey({
  required String vaultPath,
  required String accountId,
  required List<int> deviceVaultKey,
}) => RustLib.instance.api.crateApiMobileDiscardPendingContentKey(
  vaultPath: vaultPath,
  accountId: accountId,
  deviceVaultKey: deviceVaultKey,
);

Future<bool> restoreContentKey({
  required String vaultPath,
  required String accountId,
  required List<int> deviceVaultKey,
  required List<int> recoveryKey,
  required int keyVersion,
  required List<int> recoverySalt,
  required List<int> recoveryNonce,
  required List<int> recoveryCiphertext,
}) => RustLib.instance.api.crateApiMobileRestoreContentKey(
  vaultPath: vaultPath,
  accountId: accountId,
  deviceVaultKey: deviceVaultKey,
  recoveryKey: recoveryKey,
  keyVersion: keyVersion,
  recoverySalt: recoverySalt,
  recoveryNonce: recoveryNonce,
  recoveryCiphertext: recoveryCiphertext,
);

Future<BridgeDeviceApprovalRequestKey> createDeviceApprovalRequest({
  required String vaultPath,
  required String accountId,
  required List<int> deviceVaultKey,
  required String requestId,
  required BigInt expiresAtUnixMs,
}) => RustLib.instance.api.crateApiMobileCreateDeviceApprovalRequest(
  vaultPath: vaultPath,
  accountId: accountId,
  deviceVaultKey: deviceVaultKey,
  requestId: requestId,
  expiresAtUnixMs: expiresAtUnixMs,
);

Future<BridgeDeviceApprovalRequestKey?> loadDeviceApprovalRequest({
  required String vaultPath,
  required String accountId,
  required List<int> deviceVaultKey,
}) => RustLib.instance.api.crateApiMobileLoadDeviceApprovalRequest(
  vaultPath: vaultPath,
  accountId: accountId,
  deviceVaultKey: deviceVaultKey,
);

Future<void> discardDeviceApprovalRequest({
  required String vaultPath,
  required String accountId,
  required List<int> deviceVaultKey,
  required String requestId,
}) => RustLib.instance.api.crateApiMobileDiscardDeviceApprovalRequest(
  vaultPath: vaultPath,
  accountId: accountId,
  deviceVaultKey: deviceVaultKey,
  requestId: requestId,
);

Future<String> deviceApprovalVerificationCode({
  required String accountId,
  required String requestId,
  required List<int> requesterPublicKey,
}) => RustLib.instance.api.crateApiMobileDeviceApprovalVerificationCode(
  accountId: accountId,
  requestId: requestId,
  requesterPublicKey: requesterPublicKey,
);

Future<BridgeDeviceApprovalPackage> approveDeviceRequest({
  required String vaultPath,
  required String accountId,
  required List<int> deviceVaultKey,
  required String requestId,
  required List<int> requesterPublicKey,
}) => RustLib.instance.api.crateApiMobileApproveDeviceRequest(
  vaultPath: vaultPath,
  accountId: accountId,
  deviceVaultKey: deviceVaultKey,
  requestId: requestId,
  requesterPublicKey: requesterPublicKey,
);

Future<bool> completeDeviceApproval({
  required String vaultPath,
  required String accountId,
  required List<int> deviceVaultKey,
  required String requestId,
  required List<int> approverPublicKey,
  required List<int> nonce,
  required List<int> ciphertext,
  required int keyVersion,
  required List<int> recoverySalt,
  required List<int> recoveryNonce,
  required List<int> recoveryCiphertext,
}) => RustLib.instance.api.crateApiMobileCompleteDeviceApproval(
  vaultPath: vaultPath,
  accountId: accountId,
  deviceVaultKey: deviceVaultKey,
  requestId: requestId,
  approverPublicKey: approverPublicKey,
  nonce: nonce,
  ciphertext: ciphertext,
  keyVersion: keyVersion,
  recoverySalt: recoverySalt,
  recoveryNonce: recoveryNonce,
  recoveryCiphertext: recoveryCiphertext,
);

Future<BridgeHostKey> probeHostKeyMobile({
  required String host,
  required int port,
  required BigInt timeoutMs,
}) => RustLib.instance.api.crateApiMobileProbeHostKeyMobile(
  host: host,
  port: port,
  timeoutMs: timeoutMs,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MobileAgentChannel>>
abstract class MobileAgentChannel implements RustOpaqueInterface {
  Future<String> requestJson({
    required PlatformInt64 sentAtUnixMs,
    required String requestJson,
  });
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MobilePortForward>>
abstract class MobilePortForward implements RustOpaqueInterface {
  Future<String> localAddress();

  Future<void> stop();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MobileSshSession>>
abstract class MobileSshSession implements RustOpaqueInterface {
  static Future<MobileSshSession> connect({
    required BridgeConnectionConfig config,
    required BridgeAuthentication authentication,
  }) => RustLib.instance.api.crateApiMobileMobileSshSessionConnect(
    config: config,
    authentication: authentication,
  );

  Future<void> disconnect();

  Future<BridgeCommandOutput> execute({required String command});

  Future<BridgeAgentInstallResult> installAgent({
    required List<int> binary,
    required String version,
    required String expectedSha256,
  });

  Future<MobileAgentChannel> openAgent();

  Future<MobileTerminal> openTerminal({
    required String term,
    required int columns,
    required int rows,
  });

  Future<MobilePortForward> startLocalForward({
    required String bindAddress,
    required int localPort,
    required String targetHost,
    required int targetPort,
  });
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MobileTerminal>>
abstract class MobileTerminal implements RustOpaqueInterface {
  Future<void> close();

  Future<BridgeTerminalEvent> nextEvent();

  Future<void> resize({required int columns, required int rows});

  Future<void> write({required List<int> bytes});
}

class BridgeAgentInstallResult {
  final String version;
  final String remotePath;
  final String sha256;

  const BridgeAgentInstallResult({
    required this.version,
    required this.remotePath,
    required this.sha256,
  });

  @override
  int get hashCode => version.hashCode ^ remotePath.hashCode ^ sha256.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeAgentInstallResult &&
          runtimeType == other.runtimeType &&
          version == other.version &&
          remotePath == other.remotePath &&
          sha256 == other.sha256;
}

@freezed
sealed class BridgeAuthentication with _$BridgeAuthentication {
  const BridgeAuthentication._();

  const factory BridgeAuthentication.password({required String password}) =
      BridgeAuthentication_Password;
  const factory BridgeAuthentication.privateKey({
    required String pem,
    String? passphrase,
  }) = BridgeAuthentication_PrivateKey;
}

class BridgeCommandOutput {
  final Uint8List stdout;
  final Uint8List stderr;
  final int? exitStatus;

  const BridgeCommandOutput({
    required this.stdout,
    required this.stderr,
    this.exitStatus,
  });

  @override
  int get hashCode => stdout.hashCode ^ stderr.hashCode ^ exitStatus.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeCommandOutput &&
          runtimeType == other.runtimeType &&
          stdout == other.stdout &&
          stderr == other.stderr &&
          exitStatus == other.exitStatus;
}

class BridgeConnectionConfig {
  final String host;
  final int port;
  final String username;
  final String acceptedHostKeySha256;
  final BigInt connectTimeoutMs;
  final BigInt inactivityTimeoutMs;

  const BridgeConnectionConfig({
    required this.host,
    required this.port,
    required this.username,
    required this.acceptedHostKeySha256,
    required this.connectTimeoutMs,
    required this.inactivityTimeoutMs,
  });

  @override
  int get hashCode =>
      host.hashCode ^
      port.hashCode ^
      username.hashCode ^
      acceptedHostKeySha256.hashCode ^
      connectTimeoutMs.hashCode ^
      inactivityTimeoutMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeConnectionConfig &&
          runtimeType == other.runtimeType &&
          host == other.host &&
          port == other.port &&
          username == other.username &&
          acceptedHostKeySha256 == other.acceptedHostKeySha256 &&
          connectTimeoutMs == other.connectTimeoutMs &&
          inactivityTimeoutMs == other.inactivityTimeoutMs;
}

class BridgeContentKeyInitialization {
  final String deviceId;
  final int keyVersion;
  final Uint8List recoveryKey;
  final Uint8List recoverySalt;
  final Uint8List recoveryNonce;
  final Uint8List recoveryCiphertext;

  const BridgeContentKeyInitialization({
    required this.deviceId,
    required this.keyVersion,
    required this.recoveryKey,
    required this.recoverySalt,
    required this.recoveryNonce,
    required this.recoveryCiphertext,
  });

  @override
  int get hashCode =>
      deviceId.hashCode ^
      keyVersion.hashCode ^
      recoveryKey.hashCode ^
      recoverySalt.hashCode ^
      recoveryNonce.hashCode ^
      recoveryCiphertext.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeContentKeyInitialization &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          keyVersion == other.keyVersion &&
          recoveryKey == other.recoveryKey &&
          recoverySalt == other.recoverySalt &&
          recoveryNonce == other.recoveryNonce &&
          recoveryCiphertext == other.recoveryCiphertext;
}

enum BridgeContentKeyStatus { missing, pendingRecoveryConfirmation, ready }

class BridgeDeviceApprovalPackage {
  final Uint8List approverPublicKey;
  final Uint8List nonce;
  final Uint8List ciphertext;
  final int keyVersion;
  final String verificationCode;

  const BridgeDeviceApprovalPackage({
    required this.approverPublicKey,
    required this.nonce,
    required this.ciphertext,
    required this.keyVersion,
    required this.verificationCode,
  });

  @override
  int get hashCode =>
      approverPublicKey.hashCode ^
      nonce.hashCode ^
      ciphertext.hashCode ^
      keyVersion.hashCode ^
      verificationCode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeDeviceApprovalPackage &&
          runtimeType == other.runtimeType &&
          approverPublicKey == other.approverPublicKey &&
          nonce == other.nonce &&
          ciphertext == other.ciphertext &&
          keyVersion == other.keyVersion &&
          verificationCode == other.verificationCode;
}

class BridgeDeviceApprovalRequestKey {
  final String requestId;
  final Uint8List publicKey;
  final Uint8List requestToken;
  final String verificationCode;
  final BigInt expiresAtUnixMs;

  const BridgeDeviceApprovalRequestKey({
    required this.requestId,
    required this.publicKey,
    required this.requestToken,
    required this.verificationCode,
    required this.expiresAtUnixMs,
  });

  @override
  int get hashCode =>
      requestId.hashCode ^
      publicKey.hashCode ^
      requestToken.hashCode ^
      verificationCode.hashCode ^
      expiresAtUnixMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeDeviceApprovalRequestKey &&
          runtimeType == other.runtimeType &&
          requestId == other.requestId &&
          publicKey == other.publicKey &&
          requestToken == other.requestToken &&
          verificationCode == other.verificationCode &&
          expiresAtUnixMs == other.expiresAtUnixMs;
}

class BridgeHostKey {
  final String algorithm;
  final String fingerprintSha256;

  const BridgeHostKey({
    required this.algorithm,
    required this.fingerprintSha256,
  });

  @override
  int get hashCode => algorithm.hashCode ^ fingerprintSha256.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeHostKey &&
          runtimeType == other.runtimeType &&
          algorithm == other.algorithm &&
          fingerprintSha256 == other.fingerprintSha256;
}

@freezed
sealed class BridgeTerminalEvent with _$BridgeTerminalEvent {
  const BridgeTerminalEvent._();

  const factory BridgeTerminalEvent.stdout({required Uint8List bytes}) =
      BridgeTerminalEvent_Stdout;
  const factory BridgeTerminalEvent.stderr({required Uint8List bytes}) =
      BridgeTerminalEvent_Stderr;
  const factory BridgeTerminalEvent.exit({required int status}) =
      BridgeTerminalEvent_Exit;
  const factory BridgeTerminalEvent.closed() = BridgeTerminalEvent_Closed;
}
